const AppTexts = {
  metadata: {
    auth: 'Account | Acme Inc',
    login: 'Sign in | Acme Inc',
    register: 'Create account | Acme Inc',
    forgotPassword: 'Forgot password | Acme Inc',
    resetPassword: 'Create a new password | Acme Inc',
  },
  pageNames: {
    login: 'Login',
    register: 'Register',
    forgotPassword: 'Forgot Password',
    resetPassword: 'Reset Password',
  },
  brand: {
    productName: 'Acme',
    companySuffix: ' Inc',
    copyright: '© 2026 Acme Inc.',
    footerSeparator: '·',
    backToWorkspace: 'Back to workspace',
  },
  auth: {
    login: {
      title: 'Welcome back',
      description: 'Sign in to your account to continue',
      button: 'Sign in',
      loading: 'Signing in...',
    },
    register: {
      title: 'Create your account',
      description: 'Get started with your workspace',
      button: 'Create account',
      loading: 'Creating account...',
      success: 'Account created. You can now sign in.',
    },
    forgotPassword: {
      title: 'Forgot your password?',
      description: "Enter your email address and we'll send you a link to reset your password.",
      button: 'Send reset link',
      loading: 'Sending reset link...',
      successTitle: 'Check your email',
      successDescription: "If an account exists for this email, we've sent instructions to reset your password.",
      successAction: 'Back to sign in',
      footerPrompt: 'Remember your password?',
    },
    resetPassword: {
      title: 'Create a new password',
      description: 'Choose a strong password for your account.',
      button: 'Reset password',
      loading: 'Resetting password...',
      successTitle: 'Password updated',
      successDescription: 'Your password has been successfully changed.',
      expiredTitle: 'Reset link expired',
      expiredDescription: 'The password reset link is no longer valid. Please request a new one.',
      expiredAction: 'Request a new reset link',
    },
  },
  fields: {
    email: 'Email',
    emailPlaceholder: 'you@example.com',
    fullName: 'Full name',
    firstName: 'First name',
    lastName: 'Last name',
    firstNamePlaceholder: 'John',
    lastNamePlaceholder: 'Doe',
    fullNamePlaceholder: 'John Doe',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    createPasswordPlaceholder: 'Create a password',
    newPassword: 'New password',
    newPasswordPlaceholder: 'Enter your new password',
    confirmPassword: 'Confirm password',
    confirmPasswordPlaceholder: 'Confirm your password',
    confirmNewPasswordPlaceholder: 'Confirm your new password',
    rememberMe: 'Remember me',
  },
  password: {
    show: 'Show password',
    hide: 'Hide password',
    showConfirm: 'Show confirm password',
    hideConfirm: 'Hide confirm password',
    requirementsTitle: 'Password requirements',
    requirements: {
      minLength: 'At least 8 characters',
      uppercase: 'One uppercase letter',
      lowercase: 'One lowercase letter',
      number: 'One number',
    },
    strength: {
      strong: 'Strong',
      gettingThere: 'Getting there',
      needsWork: 'Needs work',
    },
  },
  validation: {
    login: 'Enter a valid email address and password to continue.',
    register: 'Complete all required fields and enter a valid email address.',
    registerTerms: 'Please accept the Terms of Service and Privacy Policy to continue.',
    forgotPassword: 'Enter a valid email address to continue.',
    resetPassword: 'Enter a new password and confirm it to continue.',
    registerPasswordRequirements: 'Choose a password that meets all the listed requirements.',
    resetPasswordMinLength: 'Your password must be at least 8 characters long.',
    resetPasswordComplexity: 'Include at least one uppercase letter, one lowercase letter, and one number.',
    passwordsMismatch: 'Your passwords do not match.',
  },
  terms: {
    agreement: 'I agree to the',
    conjunction: 'and',
    service: 'Terms of Service',
    privacy: 'Privacy Policy',
  },
  actions: {
    forgotPassword: 'Forgot password?',
    createAccount: 'Create an account',
    alreadyHaveAccount: 'Already have an account?',
    doNotHaveAccount: "Don't have an account?",
    signIn: 'Sign in',
    backToSignIn: 'Back to sign in',
    previewNotice: 'Preview only. No authentication request was sent.',
    divider: 'OR',
  },
} as const

export default AppTexts